version: "3.8"
services:
  ms_sql:
    container_name: ms-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ms_admin_123
    volumes:
      - ms_sql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: unless-stopped

volumes:
  ms_sql_data: