server:
  port: 8150
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=test_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: ms_admin_123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
